baseURL= "https://til.neilmagee.com/"
languageCode= "en-gb"
title= "TIL"
paginate = 7
theme = "comfortable-basic"
pluralizelisttitles = false

[params]
  author = "Neil Magee"
  authorwebsite = "http://neilmagee.com"

[taxonomies]
  category = "categories"
  tag = "tags"