baseURL= "https://til.neilmagee.com/"
languageCode= "en-gb"
title= "Front-end web development | Neil Magee"
paginate = 7
theme = "comfortable-basic"
pluralizelisttitles = false
pygmentsUseClasses = true
enableRobotsTXT = false

[params]
  siteName = "TIL"
  author = "Neil Magee"
  authorwebsite = "https://neilmagee.com"
  useHighlightJS = true
  description = "A blog for Neil Magee, a Lead Front-end Developer. Showing code examples of CSS, JavaScript, React and other areas of web development."
  keywords = [ "front-end", "developer", "javascript", "css", "react" ]

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/post/:title/"